# Do hyperparameter setting here
vit_linear:
    lr: 0.01
    wd: 0.01
    epochs: 100
    optimizer: 'sgd'
    scheduler: 'multi_step'
    momentum: 0.99
    net_class: ViTLinear
    batch_size: 32
    milestones: [60, 80]
    gamma: 0.1

